library RunnerLib;

/* WARNING: code generated using the Dart Toolkit for Adobe Flash Professional - do not edit */

import 'dart:html' as html;
import 'dart:async';
import 'dart:math';
import 'package:stagexl/stagexl.dart';

/* STAGE CONTENT */

class Runner extends MovieClip {
	Player instance;

	Runner([String mode, int startPosition, bool loop])
			: super(mode, startPosition, loop, {}) {
		// Layer 3
		instance = new Player()
		..setTransform(188.2,160.3,0.947,0.947,0,0,0,-2.7,-121.3);

		timeline.addTween(_tween({}).to({"state":[{"t":instance}]}).wait(30));

	}
}


/* LIBRARY */

class _Player_Thigh_Right extends Sprite {
	Shape shape;
	Shape shape_1;
	Shape shape_2;
	Shape shape_3;

	_Player_Thigh_Right() {
		// Calque 1
		shape = _draw(20.7,4.4)
		.lf([0xFF030118,0xFF0D023E],[0,1],0,16.1,5.9,3).s().p("ADLCXIgfgXIBSgKIhTgLIgbAFQgaAGgagBQhcAAhQgcQhQgdgsAAQhVAAAAgJQAAgGgJgDIgYgJQgKgFgGgHQgHgUgFgaQgDgUAEgMIARgmQANgeApgMIAygQQgIAjAAASQAAA/AqAVQAZAMBbAFQBmAIBEAUQBwAiBkBNQgrAWgkAAQgHAAgPgLgAEyBkQgBgGgJgWQAOABAKgJQAJgKAAgMQANABACAEIABAGIgBABIgPgMQAGAFAJASQAJAUAAAHQgCAZgRAJIgcgagAjXiZIBggHIgOAGIgDAAIAFAAIgBACIgBABQgTgBgOAUQgNATAAAbQgIgJgcg6g").shape;

		shape_1 = _draw(25.6,3.7)
		.f(0xFF1291C7).s().p("AAsAlQhDgUhogJQhagHgZgKQgrgVAAg/QAAgSAJgjIAMAAQAdA6AHAJIAFAIQAlAPAiAKQBAAVBqALQArAEBVAsQBSAtAUABQAIAVABAGIAdAaIgeAOQhkhNhwghg").shape;

		shape_2 = _draw(22.3,4.7)
		.f(0xFF0B0233).s().p("ACkCfQgMgWgdgCQguAGgqAAQhNABg1gfQg+gkhEgGQhEgHgSgKQgRgJgLgJQgMgIgCgIQAGAHAJAFIAYAJQAJADAAAGQAAAJBVAAQAtAABPAdQBQAcBdAAQAZABAbgGIAagFIBTALIhSAKIAgAXQAPALAHAAQAkAAArgWIAegOQARgJABgZQAAgHgJgUQgJgSgFgFIAPAMIAAgBIAAgGQgCgEgNgBQgRgPhEgkQhBglgIgKQgagfg5giQhJgqhAAAQhBAAgTALIACgCIgGAAIADAAIAOgGQARgGA6gJQAjAAAZAHQAeAJA2AbQAcAOA3AzQAyAvAfALQA7ARAZAcQAWAZAAAlQAAAcglAZQgtAfhNAAQgTAAgMgUg").shape;

		shape_3 = _draw(28.2,-0.1)
		.f(0xFF180479).s().p("AB4BJQhVgugpgFQhsgKhAgTQgigLglgPIgFgHQAAgbAOgTQANgUAUAAIAAAAQATgLBBAAQBBAABIAqQA5AhAaAgQAIAKBBAiQBEAnARAPQAAAMgKAJQgKAJgNAAQgUAAhSgtg").shape;

		addChild(shape_3);
		addChild(shape_2);
		addChild(shape_1);
		addChild(shape);
	}
}

class _Player_Thigh_Left extends Sprite {
	Shape shape;
	Shape shape_1;
	Shape shape_2;

	_Player_Thigh_Left() {
		// Calque 1
		shape = _draw(21.1,11.7)
		.f(0xFF0D023E).s().p("ACICCIA7AQIgEgDQgXgSgRgGQgHgCgYgDQhfgNh7g+QiThFg0hJIACgBIgDgBIgEgNQAFgXAkgSQAkgTBLgQIgZAjQAEACBAAEQgQAEgSANQgPAMAAAFQAAA9BuAsQAfANBaAWQAUAFCYBDQAMAHANALIAIAOQAKAPANAGQgNAQgHAUQgEANgGAAQg3AAhShBg").shape;

		shape_1 = _draw(29.3,11.3)
		.f(0xFF180479).s().p("ADFCBIgHgOQgNgKgNgIQiYhDgSgFQhcgXgfgLQhtgtAAg9QAAgFAPgLQARgOAQgDQBSgHB6BZQAmAbBWBLQAXAUAyAeQAcARAAASIgFAKQgGAKgIAJQgNgGgKgPg").shape;

		shape_2 = _draw(23,12.2)
		.f(0xFF0B0233).s().p("ADMDAQgJgDgbgRQhEgqh6gkQh4gkhrhbQhJhBAGgKQAzBJCTBFQB8A+BfAOQAXACAHACQARAGAXATIAEACIg6gPQBRBAA3AAQAHAAAEgNQAGgUANgQQAIgJAGgKIAFgKQAAgSgcgRQgygegXgUQhWhLgmgbQh6hahSAIQg/gEgFgDIAagjQB3AaBSAyQBUAxAjAkQAjAlAFABQAjAXA2AiQAmAbAAAWQAAAHgeArQgdAsgFAAQgfAAgTgIg").shape;

		addChild(shape_2);
		addChild(shape_1);
		addChild(shape);
	}
}

class _Player_Shoulder_Right extends Sprite {
	Shape shape;
	Shape shape_1;
	Shape shape_2;
	Shape shape_3;
	Shape shape_4;
	Shape shape_5;
	Shape shape_6;
	Shape shape_7;
	Shape shape_8;
	Shape shape_9;
	Shape shape_10;
	Shape shape_11;
	Shape shape_12;

	_Player_Shoulder_Right() {
		// Calque 1
		shape = _draw(-18.9,25.1)
		.f(0xFFCF764B).s().p("AgSAqQALgVAJggQALgfACgPIAAgDQAEAGAAAIQgBAJgNAmQgHAZgEAYIgCgDIgCgDQgEgDAAAHIABACIgCAEIAAAFIAAACg").shape;

		shape_1 = _draw(-20.3,30.9)
		.f(0xFFCF774C).s().p("AAGAPIgDgCIAAAAIgBgBQgCgBgBgFQgDgGgBgJIABgFIADARIAAgCIAAgDIABgEIAAgCQAAgHACADIACADIACADIAAACIAAATg").shape;

		shape_2 = _draw(-19.6,32.4)
		.f(0xFFBA643E).s().p("AAAAAIAAAAIAAAAIAAAAg").shape;

		shape_3 = _draw(-34.4,34.3)
		.f(0xFF333333).s().p("AAAAAIAAAAIAAAAIAAAAIAAAAg").shape;

		shape_4 = _draw(-18.2,20.6)
		.f(0xFF552D17).s().p("AAICBQAHAAAJgCQAygMASgTQASgTApg+QAHAIAHAKQg1BAgVAKIhAAfIgTgJgAigCIIgCAAQgBgIAAgKQgBgMAVgcQAWggAGgYQAMg2AJgZQAUg6AcgXQARAEAIAFQgZAUgwBnIhACJIgCAFg").shape;

		shape_5 = _draw(-27.1,22.5)
		.f(0xFFBA643F).s().p("AhHCLQgEgKAEgMIAAABIAAgBIACgFIBAiJQAuhnAZgUIAIAEQg/BFgBASQAAATACAQQABARgPAoQgRArgiBHIgCAAQgLAAgFgKg").shape;

		shape_6 = _draw(-13.3,27.4)
		.f(0xFFEA9B71).s().p("AhVAzQgTgLACgLQADgLAXgpQAXgrAOgOQgCAPgLAfQgLAigLATIgBAFQABALADAGQACAFADABIABABIAAABIAAgBIADACIAAAAIAAAAIAAAAIAUAHQAtgKAqgmQAqglABgrIAPAUQgqA8gSATQgSATgwAMQgIACgHAAIASAJIgMALIg1gegAg+AwIABgBIgBABIAAAAg").shape;

		shape_7 = _draw(-18.5,23.4)
		.lf([0xFFF19761,0xFFB9623E],[0,1],3.4,-6.9,3.4,18.5).s().p("AhKCbQgWgCgrgNQAihIARgqQARgpgBgQQgCgRABgSQAAgTA/hFQAoAXBuBkQgBApgqAnQgqAmgvAKIgSgHIAAgBIAAAAIAAgUIAAgCQAEgYAHgZQANgmABgJQAAgIgEgGIAAADQgMAOgYApQgXArgCALQgCALATALIAzAeQgOASgbAJQgYAHgUAAIgHAAgAgKBXIAAABIAAABIABABIgBgCIABgBIgBAAgAgNBYIAAAAIAAABg").shape;

		shape_8 = _draw(-8.2,5.7)
		.f(0xFF1291C7).s().p("AgOATQgCgDgMgIQAPgJACgEQACgDAHgXIABgCIAOAVIAQAMIgBACQgKAMgXAUIgJgPg").shape;

		shape_9 = _draw(-5.1,5.3)
		.f(0xFF0D023E).s().p("AAZBjQgigdgNgIIADADQgPgIgRgFIAPgOQAYgUAKgMQAfAYBRARQASAAASgDQgKAdgdAXQgbAWgTAAQgNAAgXgTgAiRAOQANgKAVgzQAUgwAqgWQgKAmAaA0QgIAXgBADQgDACgPALIgSAHQgMAFgOALQgZgOgQgHg").shape;

		shape_10 = _draw(-5.2,1.9)
		.f(0xFF15ABEA).s().p("AhnBFQAOgLAMgFIASgHQAMAIADADIAJAPIgPAOIgLAMQgSgOgYgPgAgPAYIgRgVQAvhXAYgNIAgAKIAgAMQgQALgoAsQgkAmgLAUIgPgOg").shape;

		shape_11 = _draw(-5.3,6.7)
		.f(0xFF0B0233).s().p("AAXCaIgOgUQhshkgqgWIgJgEQgHgFgSgDQAhgQANgSQAIgMAOgnQAPgsAdgUQAggVA2gBQA6AAAsAlQAzAqAABFQAAA9gjAsQgmAsg6gCIgCAPQgCATgFAOQgGgKgHgIgAAAiTQgeADgQANQgqAWgUAwQgVA1gNAIQAQAHAZAOQAXAPATANQA4AuAdA0QADgKAAgKQAAgMgKgUQgNgZgWgUIgDgCQANAHAiAeQAWATAOAAQATAAAbgWQAdgYAKgcQAIgxgHghQgIgqglgdIghgMIgfgKQgMgDgOAAIgPABg").shape;

		shape_12 = _draw(-0.7,6.6)
		.f(0xFF180479).s().p("AhqAyIALgMQARAGAPAHQAZAUANAZQAJATAAAMQAAAKgDALQgfg0g4gugAgugFIACgDQAMgTAjgpQAngsARgKQAkAdAJAqQAHAggJAyQgRACgTAAQhPgQghgWgAhdiCQARgNAfgDQAYgCASAEQgZANgwBYIgBACQgZg0AJglg").shape;

		addChild(shape_12);
		addChild(shape_11);
		addChild(shape_10);
		addChild(shape_9);
		addChild(shape_8);
		addChild(shape_7);
		addChild(shape_6);
		addChild(shape_5);
		addChild(shape_4);
		addChild(shape_3);
		addChild(shape_2);
		addChild(shape_1);
		addChild(shape);
	}
}

class _Player_Shoulder_Left extends Sprite {
	Shape shape;
	Shape shape_1;
	Shape shape_2;
	Shape shape_3;
	Shape shape_4;
	Shape shape_5;
	Shape shape_6;

	_Player_Shoulder_Left() {
		// Calque 1
		shape = _draw(0,29.1)
		.lf([0xFFF19761,0xFFB9623E],[0,1],-69.4,56.4,-82.9,65).s().p("Ag0B3QgTgNAAgSQABgCAGgeQACAMAGAJQAGAIAEAAQAPAAANgoQALgjAAgaIgGg7QgDgYAPgdQAcgFANACQAHAAAQAHQAEAJACAOQADANAAAIQAAASgjBXQgaBAgSArQgaAAgTgNg").shape;

		shape_1 = _draw(4.4,29.5)
		.f(0xFFBA643F).s().p("AgGAWQAhhXAAgTQAAgHgDgOQgCgOgEgIQAPgBAKASQAKASAAAaIgdBBQgVAvgBAGIgSAqQgTAfgRAEQAUgsAag/g").shape;

		shape_2 = _draw(0.4,29.6)
		.f(0xFF552D17).s().p("AhXAIIgJhBQADgMADgDIAHgJIAPB8IAAAIQgGAegCABQgEgUgHg2gABBgCIAchCIAEAcQgIASgVAiQgUAggFAHQABgGAVgvg").shape;

		shape_3 = _draw(-4.1,26.9)
		.f(0xFFEA9B71).s().p("AgOBjQgHgJgBgMIAAgIIgPh8QALgSAKgJQAWgVAggEQgOAdACAYIAHA5QAAAcgMAkQgNAngNAAQgDAAgGgIg").shape;

		shape_4 = _draw(3,5.7)
		.f(0xFF0D023E).s().p("ABHCMQgLgZgagOQgUgLgOAAQgKAAgRADIAGgKQADgFAAgGQAAgIgGgHQgHgIgMAAQgUAAgEADQgDACgLALQADgGgLAIIgNALIgFgQQAIhRBBgxIAoggQATgQAAgRIgZgMIAWgCIgQgCQAugBASALQAmAZAABUQAAAKgJAdQgJAhgJAQQgHgKgJgIIAAACIAIASQAIAWAAAfQAAAOgIAXg").shape;

		shape_5 = _draw(-1,5)
		.f(0xFF180479).s().p("Ag+B+IALgbIALgbQALgLAEgBQADgEAUAAQAKAAAIAJQAFAGAAAJQAAAGgDAFIgGAJQgdAHgTAKQgPAHgOAOgAgihMQAgg9AqAAIAaAMQABARgUAQIgqAfQg+AygJBRQAAhUAgg+g").shape;

		shape_6 = _draw(0.9,8.1)
		.f(0xFF0B0233).s().p("ABYCRQAAgZgKgSQgKgSgOAAQgQgHgHAAQgNgCgdAFQggAEgXAVQgLAJgLASIgGAJQgDAEgEALQgCgNAAgKQAAgJAIgcIAIgcIgOgeQgMgdAAgfQAAg7AdgnQAlgyBLgCIAQABIgXADQgqAAggA9QggA9AABVIAEAQIAOgLQALgIgDAFIgMAbIgLAbIgCAMQANgOAPgHQATgKAggHQAOgCALAAQAPAAAVAKQAaAPALAYIACALQAHgYABgNQAAgggJgWIgIgSIABgCQAJAJAHAKQADAGAEASQAFAUgBAMQABAkgXAug").shape;

		addChild(shape_6);
		addChild(shape_5);
		addChild(shape_4);
		addChild(shape_3);
		addChild(shape_2);
		addChild(shape_1);
		addChild(shape);
	}
}

class _Player_Shin_Right extends Sprite {
	Shape shape;
	Shape shape_1;
	Shape shape_2;
	Shape shape_3;
	Shape shape_4;
	Shape shape_5;
	Shape shape_6;
	Shape shape_7;

	_Player_Shin_Right() {
		// Calque 1
		shape = _draw(-5.8,26.3)
		.lf([0xFFF19761,0xFFB9623E],[0,1],8,-11.2,-15.1,-14.9).s().p("AgqDyIgCgLIADgPIAJhkQAJhrgahFQgIgSgMgbQgKgWAAgRQAAgLAIgMQASgaAXgyIAPAIIgCAAQgXAUgLAaQgIASAAALQAAAtARAcQAPAcAAAJQAOgMAOglQAVgxAAg2IgEgJQgEgJgFgGQAKAFAWAEQAWAEARABIgnAAIgCgBIgCA4QAICjAEAvIAKgFIgIAqIgLAqQghA1gDAqQgBAMgDACQgCADgTAAQgKAAgLgCg").shape;

		shape_1 = _draw(0.1,62.4)
		.f(0xFF112635).s().p("AgEAiQghgIgLgHQAFgKAagMQAcgPAZAAQAFAAATAFQATAEAFAAQAlAAASgRIARgRQAOAAASALQASAKAAAJQAAASgjASQgqAVhEAAQgeAAgjgKgAjMgBQADgLALgKQAKgKAHAAQASAAAkAVQAXALAVAOIACACQgIADggAEQgfAEgKAAQg7AAAJgcg").shape;

		shape_2 = _draw(5.6,49.8)
		.f(0xFF840084).s().p("AgJA7Qg0gkAAgQQAAgCAFgDIALgFQATACAQAEQAYAhAgAWQAZAQAQADIABACIgQAKIgPAKQgTgGgvgigAhLghIgMgTIAbgtIARAoQAEAMAPAdIgBABQgeABgLADQgBgHgIgPg").shape;

		shape_3 = _draw(-3.5,53.9)
		.f(0xFF660066).s().p("Ag7BCQgtgcgsADIATgtQAWgtAfgQQgCAXAAAKQAAAOAoAAQAUAAAGgOQAFgLAKgzIAMAUQAIAPABAGQgLAIgJAPQgEALAAAEQAAANAPAUQATAYAeATQgegJgeAVQgWAWgDAAQgPgPgXgOgAAoAdQgWgVgKgXQAAgHAKgLQAMgOARAAQAIAAAJAEIAQAHQgQgHgTgCIgLAIQgEACAAACQAAAQA0AjQAwAiATAFQgQADgOAAQgtAAgigfg").shape;

		shape_4 = _draw(0.3,53.5)
		.f(0xFF2B002B).s().p("AgnCBIgfgRIgcAIQgdAIgcAAQggAAgOgGQgQgGAAgQQAOgoAUgoQAnhQAdgLQAFAAADAFQAEAFAAAIIgCAPIABALQALACAKAAQATAAAEgDQADgCABgMQADgqAig1QAHgFAKgDQAOAKAUAwQAVAzAiAcQAVAQBAAQQAuALAAAfQAAAmguAWQgqAUhBAAQhHAAghgRgAgTBUQgaAOgFAKQALAHAhAIQAjAKAeAAQBEAAAqgVQAjgSAAgUQAAgJgSgKQgSgLgOAAIgRARQgSARglAAQgFAAgTgEQgTgFgFAAQgZAAgcAPgAjABBQgLAKgDALQgJAeA7AAQAKAAAfgEQAggEAIgDIgCgCQgVgPgXgMQgkgVgSAAQgHAAgKAKgAhiBHQAXAOAPAPQADAAAYgXQAegUAcAIQgcgSgTgZQgRgVAAgLQAAgFAGgLQAJgPALgHQALgDAdgCIABAAQgPgegFgLIgOgpIgcAtQgMAzgFALQgGAOgUAAQgoAAAAgOQAAgKACgXQgfAQgWAtIgTAtIAJAAQAnAAApAagAgTgcQgKALAAAHQAKAXAUAVQAtAoBAgNIAQgJIAPgKIgBgCQgPgDgZgQQghgVgaggIgQgHQgJgDgIAAQgPAAgMAOg").shape;

		shape_5 = _draw(-3.6,17.2)
		.f(0xFFEA9B71).s().p("AAOhBIADg4IACAAIAnABIAYAAQgJBDgKA2IgaCLIgKAFQgEgwgJiigAhBADQgQgaAAgtQAAgMAHgRQAMgaAXgVIANAFIAPAFQAFAGAEAJIACAJQAAA2gTAxQgQAjgOALQAAgJgQgbg").shape;

		shape_6 = _draw(-4.5,21.2)
		.f(0xFF552D17).s().p("Ag6D/QgDgFgFAAQAIhZAAgWQAAhTghg4IgXgkQgLgRAAgOQAAgkAagxQAYguAjgiIARgNQgtBHgSAlQgUAnAAAXQAAALAfA/QAfA9AAA/IgBAsIgJBlQAAgIgEgFgAAmCOIBWmLIgCAGQABgEABgQQADAFgCAXQAEgHgnDDQglCxgMAyIAEAAQgKADgHAFg").shape;

		shape_7 = _draw(-3.7,14.6)
		.f(0xFFBF6842).s().p("Ag1C9QAAg/geg/Qgfg/gBgJQABgXATgnQASglAuhHIgRANIABgBQASgcAhgTQAdgQAUgCQAUgBAUAKQAVAKABAMQgBAQgBAEIACgGIhVGLIAIgqIAZiLQAKg2AKhDIgYAAQgRgBgWgEQgVgFgKgEIgOgFIgNgFIABAAIgOgIQgXAzgSAaQgIAMgBAKQAAARAKAVQANAbAHASQAaBGgJBrg").shape;

		addChild(shape_7);
		addChild(shape_6);
		addChild(shape_5);
		addChild(shape_4);
		addChild(shape_3);
		addChild(shape_2);
		addChild(shape_1);
		addChild(shape);
	}
}

class _Player_Shin_Left extends Sprite {
	Shape shape;
	Shape shape_1;
	Shape shape_2;
	Shape shape_3;
	Shape shape_4;
	Shape shape_5;
	Shape shape_6;
	Shape shape_7;

	_Player_Shin_Left() {
		// Calque 1
		shape = _draw(-30.6,-42.7)
		.f(0xFF840084).s().p("ABDAnQgbgagHgFIABgBIgCgBQASgBAZgHIAUAPIAUASQgFAggFAMQgKgLgcgZgAAWgEIgKgDQgHgFgtgRQgwgQgJgBIgPADIgCAAIAKgPIALgPQAegGA5AWQA2AVAOAWQgOALgPAAIgLgBg").shape;

		shape_1 = _draw(-23.6,-48.4)
		.f(0xFF660066).s().p("AAaBFIgVgRIANgNIAEgGQAAgUgRgNQgVgShDgZQAtgMAUgSQAQgNACAAQAhAPAkAOQBLAcAUgDIgBABQgBANgKAdQgOAngMAIIgNgfQgBgEgDAAQgFABgTgEQgRgEgFAAQgKAAgHAEQgJAFAAAIQAAAGAEAXIAFAZIgUgSgAgiAzQAPABAOgMQgPgWg4gTQg5gWgeAHQAMgHAlgKQAhAAAuAVQArASAAAOQAAAKgIAKQgJAMgSAAIgHgBg").shape;

		shape_2 = _draw(-27.8,-47.5)
		.f(0xFF2B002B).s().p("AA4BwIgtgnQhGg6hJAAIgdAIQgcAJgEAAQgbAAAAgiQAAgyAugkQAygnBXAAQAZAAAZAKQAbAKADAAIBCgNQA9AAAZAPQAZANAAAhQAAAFgEAEQgFAEAAAFQAKAnAAAPQAAAegwAQQgLgGgJgNIgOgUIgWgBQgPABgMAGQAAAQAFAWQAGAWAAAEQgBATgEAIQgFAJgDACIgBAAQgLAAgUgQgAAWhRQgUARgrAMQBAAaAYATQARAMAAATIgFAHIgMAMQgYAKgSAAIACACIgBABQAGAEAcAaQAcAaAKALQAEgNAFggIgEgZQgEgXAAgFQAAgJAJgFQAHgEAJAAQAFAAASAEQASAEAFAAQAEAAABADIAMAgQANgJANgnQALgdABgMIAAgCQgTADhLgcQglgOgigPQgCAAgQAOgAhEARQAwARAGAFIALACIAIACIAIAAQASAAAKgMQAJgKAAgKQAAgLgtgVQgtgVghAAQgkAKgMAHIgLAPIgKAMIACABIAPgDQAJAAAwARgAiWhXQg8AdAAA2QAAAQAUAAQAZAAAYggQAXgiAsAAQAvAAAVgOIAbgeQgGgEgRgEQgUgFgJAAQhGAAgxAYgAAzhkIAKAFIBXAhQAiAMAKAAQAEAAAEgEQAEgGAAgLQAAgZgXgGQgOgDgbAAQgiAAg3AFg").shape;

		shape_3 = _draw(-28.1,-52.5)
		.f(0xFF112635).s().p("AjOAsQgBg0A8gdQAxgYBGAAQAJAAATAFQASAEAGAEIgbAeQgVAOgvAAQgsAAgXAgQgYAigZAAQgTAAAAgSgACXgMIhXghIgJgEQBigLAfAJQAYAFAAAZQgBAMgEAFQgDAEgFAAQgKAAgigMg").shape;

		shape_4 = _draw(-6.2,-18.2)
		.f(0xFFBF6842).s().p("AgqBGIhMj0QAEgIABgTQAQAnAUBLIAjB9QApCUAmAAQAJAAAegKQAfgLAMgIQgXAthIAAQgZAAgpiEg").shape;

		shape_5 = _draw(0,-20.2)
		.f(0xFFEA9B71).s().p("AgWAkQgshCgEg4IAEgTQBeBDAKALQAgAiABBJIgCAVIAAADQgBACgGAAQgnAAgthGg").shape;

		shape_6 = _draw(-4.7,-21.1)
		.f(0xFF552D17).s().p("Ag9CDQgKgjgXhVQgXhSgXg/QACgCAFgJIBMD0QApCEAZgBQBIAAAXgsQAJgOAOhLQAAhCgRgeQgLgTgigYQgsgfgXgdQgugzgphZIANAUQAKAOAKAFQAUA4AkAkQAOANAyAhQAnAZAQAbQAXAkgBBEQAAA2gNAgQgdBBhQAAQgwAAgghvg").shape;

		shape_7 = _draw(-5.4,-22.6)
		.lf([0xFFF19761,0xFFB9623E],[0,1],-4.3,7.7,17.5,-0.7).s().p("AgyBSIgjh+QgUhLgQgmQAAgEgGgWQgFgWAAgQQAMgGAPgBIAWABQAqBYAsA0QAZAcAsAfQAiAZALASQAQAfAABCQgNBLgJAOQgMAIgfAKQgeAKgJAAQgmAAgpiTgAgQg+QAEA4AqBCQAuBGAoAAQAGAAAAgCIABgDIABgVQAAhJgggiQgKgLhehDg").shape;

		addChild(shape_7);
		addChild(shape_6);
		addChild(shape_5);
		addChild(shape_4);
		addChild(shape_3);
		addChild(shape_2);
		addChild(shape_1);
		addChild(shape);
	}
}

class _Player_Head_2 extends Sprite {
	Shape shape;
	Shape shape_1;
	Shape shape_2;
	Shape shape_3;
	Shape shape_4;
	Shape shape_5;
	Shape shape_6;
	Shape shape_7;
	Shape shape_8;
	Shape shape_9;
	Shape shape_10;
	Shape shape_11;
	Shape shape_12;
	Shape shape_13;
	Shape shape_14;
	Shape shape_15;
	Shape shape_16;
	Shape shape_17;
	Shape shape_18;

	_Player_Head_2() {
		// Calque 3
		shape = _draw(-16.9,-2.4)
		.f(0xFF3C003C).s().p("AhBBWIgngmQgNgNgEgNQgCgNAAggQAAgvATgrQALgWASgeIgSBZQAAAnALAOQANAJAIAHQAFgTAhguQAfguANgIQgOAdgSA4QgSAzAAAIQAAANAGALQAIANAOAAQACAAAegkIBehuQgoA5hNDBIgDAHQgjgugjgig").shape;

		shape_1 = _draw(-4.4,-8.2)
		.f(0xFF2B002B).s().p("AjeCHQgtg1AAgxQAAiXBrhIQBQg1B2AAQA1AABGAcQA/AYAsAhIgLACIgWAEIgdAFIgZAFQgFAAgeAJIgUAHIgmAWIgLAIIgHAGIgOAMQgYAcgIAMQgOAUgYAsIgHAMIgIAQIgMAVIgFAMIgaA5QgEALgDAbQgGAegcAgIhthtgAhjjLQg4AagtBFQgRAegLAXQgUAqAAAuQAAAiADAMQAEANANAOIAnAmQAiAiAmAuIADgIQBMjDAmg3QAcgpBagwQBdgxAmAKQhwhChbAAQhcAAg1AZg").shape;

		shape_2 = _draw(-2.9,-14)
		.lf([0xFF3C003C,0xFF970198],[0,1],-33.1,12.6,1.2,-21.7).s().p("AiiCeQgHgLAAgNQAAgIATg1QATg4APgbQgOAIghAsQghAugFATQgHgHgOgJQgKgOAAgnIARhXQAthFA3gbQA2gZBcAAQBbAABvBDQgmgLhdAyQhZAwgaAnIhdBwQgfAkgEAAQgOAAgHgNg").shape;

		shape_3 = _draw(22.4,-13.9)
		.f(0xFFFFDF62).s().p("AAZgKQgfgbg8gnIgCgBQAMABAdAGIAxAdQAUAMAYAUIAYAWIABAAQASAmAAAxQgZhAg7gugAgyAJQgugugjgbIAwAIQA2AHAdAxQAIAoAEA3QgGgZg4g9gAA6gnIhag4IAVgEQA3AqAgAaQAKAGAuALIgEAAQgZAAgtgZg").shape;

		shape_4 = _draw(-0.1,-0.2)
		.f(0xFFCCCCCC).s().p("AAAAAIAAAAIAAAAg").shape;

		shape_5 = _draw(-1.5,-3.3)
		.f(0xFF53D5FF).s().p("AAAAAIAAAAIAAAAg").shape;

		shape_6 = _draw(8.9,15.3)
		.f(0xFFFFFFFF).s().p("AgiABQgNgUgFgCIABAAQAJAHAdAHQAiAIAggBQgCAGgFAEIgGAFIgBABQgLAGgPAAQgdAAgSgVg").shape;

		shape_7 = _draw(7.8,13.2)
		.f(0xFF070609).s().p("AgmAPIgSgfQAUAPAkAEIAxAGQAZADAGAJQgJACgNAJQAFgFABgGQgfACgigLQgdgHgKgFIAAAAQAFAAANAWQASAWAcAAQAPAAALgHIACgBIgDADQgSANgIAAQgkAAgZglgAhPgyIABgBIAAABIgBAAg").shape;

		shape_8 = _draw(15.3,9.9)
		.f(0xFFF4AD82).s().p("AhgBcIgNgMIgBgCIgBgHQAAgGABAAQABABAAAAQABAAAAAAQAAAAAAAAQABAAAAgBIAeAQQAEADABAKIgHABQgHAAgKgDgAgBhSIAQgLIACgBQAEADAtAVQApASAFAJIgUACQg1AAgogpg").shape;

		shape_9 = _draw(12.2,-0.5)
		.f(0xFF0098CA).s().p("AhBAmIgVgHIA2gxQAWAAANAKQAPAJAAAPQgdAQgLAFQgKAEgMAAQgHAAgOgDgABaATQgIgBgNgGIgNgHQAJgHAigHIANAWQgHAGgLAAIgEAAgAB5gMIAEACQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAABIgGAKgAh2ghQAGgHAJAAQAGAAAFACIAIAEIgmAlQgHgYALgMg").shape;

		shape_10 = _draw(11.9,-2.8)
		.f(0xFF33CCFF).s().p("AAGANQgNgKgVAAQACgBADgFQAEgHAFAAQAeAAAXAJQAMACAGAEQAKAAAcgFIAIAMQgiAHgJAJIgEgEIgDABIggAOQABgPgQgLgAh3AaQgKgPgEgOIABgBQABgQAJgKQAHgIAJAAIARAEIAXAHIgOAQIgIgEQgGgCgGAAQgIAAgGAHQgLAKAGAagACBALIgEgCIAAgNIAKgBQAAAGgFAOQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBg").shape;

		shape_11 = _draw(11.7,-2.2)
		.f(0xFF006F93).s().p("AhyAlQgfgeAAgkQAAgSAHgJQAHgKARAAQAkAABKAYQAhALAeAMIAcgBIAGAIQgYADhBgWQhDgYgyAAQgKAAgGACQgEATAAAHQAAAKACAHIAAABQAEAOAKAPIAAAAQALAQAZAMIAWAHQAOADAHAAQALAAAKgEQAMgFAcgQIAggOIgEAIIgSALQgIAFgdAMQgfAMgGAAQgrAAgegegABgAkQANABAJgHIAEAJIgDADgAB9AVIAHgMQAFgMAAgIQAAgCgEgCIgGgBIgBgLQANAFADADQAEACAAAGQAAAdgXAUg").shape;

		shape_12 = _draw(11.8,-2.6)
		.f(0xFFAEEBFF).s().p("Ah2AYIAAAAIAngmIAOgPIgYgHIgQgEQgJAAgIAIQgIAJgCARIgBAAQgBgHAAgKQAAgHADgUQAHgBAKAAQAyAABDAYQBBAVAYgCIAEAGQgcAEgKAAQgGgCgMgEQgXgIgeAAQgGAAgEAGQgDAGgBAAIg3A0QgZgMgLgQgAB9gNIAHACQADABAAADIgKAAg").shape;

		shape_13 = _draw(8,5.3)
		.f(0xFFF19761).s().p("AgqDOQg3gNgZghQgcgrgSg0QgQgtAAgXQAAgFANgmQAOAPAEATQAEAOgEAPIACABQALgNAIgSQAHgUAAgRQgHgqgHgQQAagtAOgUQAIgMAYgcQAaACApAIIAEACQghAKgOAIQgIAEgMALIABgBIAEgCIgIAIIgCACIAGABQBSgaAPACQAeAQAeAhQAUAXAJAQIgcABQgegMgkgLQhHgYglAAQgQAAgIAKQgGAJAAASQAAAmAeAeQAfAeArAAQAEAAAfgMQAfgMAIgFQAxAuBBgJQABAKgKAOQgaASgmAFQghAEgSgHQAEANAWARQAVAPAKAAIgfBWQgTAmgmAAQglAAgigIgAgeCUQAOAKAVAAQANAAAHgDQAGgDAHgJQgJADgXgDQgVgCgIgDQAQAFAHgDQAAgKgFgDIgdgQQAAAAgBABQAAAAAAAAQAAAAgBAAQAAgBgBAAQgBAAAAAGIABAHIgJgKQAAAWAQAMgAgoBfQAZAkAkAAQAIAAASgNIADgDIAGgEQANgJAJgCQgGgIgZgEIgxgGQgkgGgUgPIASAigAhRAbIABABIAAgCg").shape;

		shape_14 = _draw(5.9,7.2)
		.f(0xFF552D17).s().p("AguDTIAHgKQg6gQgthDQgjg1gEgmIgBAEIgVBIIgCAIIgQgKIAEgLQAcghAGgeQADgbAEgJQACAWANAmQAWA9AmAdQAZAhA3ANQAgAIAnAAQAmAAATgmIAfhWIAKgYQgYAAgMgDIgJgDIgJgHQARAGAPgBQALAAAVgHQAZgLANgPQAKgNgBgJQgFgJgpgSQgsgVgEgEIgCACIAEgIIADgBIAEAEIAMAHQAOAGAIAAIAWAHQAVAHANAKQAMAIAAAHQAAASgeAZQgkAegNArQgWBLgMAPQgVAbg9ABQgvgBgLAHgAgWjLQAOgHAhgKIAeAQQgQgEgKABQgdAAgQAFIgVAMIgEACIgBABQAMgLAIgFg").shape;

		shape_15 = _draw(5.4,5.5)
		.f(0xFFCD784B).s().p("AjICAIACgIIAVhIIABgDQAEAlAjA1QAtBDA6ARIgHAKgAicBEQgNgmgCgYIAag2IAAAAQgNAmAAAFQAAAXAQAtQASA0AcArQgmgdgWg9gAgECSQgQgMAAgWIAJAKIABACIALAMQAIADAXACQAXADAJgDQgHAJgGADQgHADgNAAQgXAAgMgKgABwBJQgWgRgEgNQASAHAhgEQAmgFAagSQgNAPgZALQgVAIgLAAQgPAAgRgGIAJAHIAJAEQAMADAYAAIgKAXQgKAAgVgPgAgqijIACgCIAIgIIAVgLQAOgGAfAAQAKAAAQADIABABQgPgChSAaIgGgBgAgpjXIAOgNIA0AYQgogJgagCg").shape;

		shape_16 = _draw(13.4,-8.9)
		.f(0xFFDDB000).s().p("AjICLQACgNgGgQQgGgSgKgJIALgVQAAADAIAaQAHAWgEAbgACmAhIgIgEIgdgLIgHgGQgZgVAAggIAqAiQAkAaAIAPIgRgBgAABglQg0gngygMIAMgJQA/AaAcAYQAWASAlArQgWgYgmgbgAC0giIgYgYIAhAMQARgCAPgIQgGAGgNAHQgPAIgGABgAgphyIgKgEIATgHIAlAUgAAUh+IACABIgVgJIAagFIAiAUQgdgGgMgBg").shape;

		shape_17 = _draw(14.1,-9.2)
		.f(0xFFFFCC00).s().p("AjNCPQAFgbgHgXQgIgZAAgEIAJgQIAHAaIAFAUQAAAIgEAQQgCARgEAIgABPA1IgZgkQgkgsgUgRQgegYhAgaIAngVIAKAEQAiAcAtAwQA6A6AGAZIACAdIgBAQIgSgogACxAlQgIgPgkgaIgrgjIgNgVIAEAOQgcgyg1gHIgmgUQAegIAFgBIATAKQA8AnAhAaQA6AxAaA+IgQgRgACWg4QgZgUgTgLIgzgdIgjgUIAdgFIBdA3QAxAcAZgCIgBAHQgQAIgQACg").shape;

		shape_18 = _draw(13.9,-8.5)
		.f(0xFF796100).s().p("AjUCbQAEgPgEgPQgEgUgOgPIAAAAIAGgMQAKAJAGASQAGAQgCANIABABIABAAQAEgIACgRQAEgPAAgIIgFgUIgHgaIAGgMQAIAQAGApQABARgIAVQgIATgLANgABgBdIgNgYIgIgOIgEgHIgGgIQgIgQgVgXQgegegcgQIgBgBIgegQIgFgCIg2gYIAHgFQAyAMA2AnQAjAcAWAXIAZAkIASApIABgQIgCgdQgFg1gKgpIgEgPIANAWQAAAgAaAVIAHAGQgRgIgIgFIAEAiIABAKIAAAGIAAAQIgCASIgCAQIgBACgADHBIQgHgbgegRIARABIAQARQAAgvgSgmQAGAAAPgIQAMgIAHgGIABgHQgugLgKgGQgggag5gqIALgCQAaARAyAqQArAgAcgKQgNAoglADQAIAJAIASQAKATAAALIgCAYQgCAQgEAGg").shape;

		addChild(shape_18);
		addChild(shape_17);
		addChild(shape_16);
		addChild(shape_15);
		addChild(shape_14);
		addChild(shape_13);
		addChild(shape_12);
		addChild(shape_11);
		addChild(shape_10);
		addChild(shape_9);
		addChild(shape_8);
		addChild(shape_7);
		addChild(shape_6);
		addChild(shape_5);
		addChild(shape_4);
		addChild(shape_3);
		addChild(shape_2);
		addChild(shape_1);
		addChild(shape);
	}
}

class _Player_Head extends Sprite {
	Shape shape;
	Shape shape_1;
	Shape shape_2;
	Shape shape_3;
	Shape shape_4;
	Shape shape_5;
	Shape shape_6;
	Shape shape_7;
	Shape shape_8;
	Shape shape_9;
	Shape shape_10;
	Shape shape_11;
	Shape shape_12;
	Shape shape_13;
	Shape shape_14;
	Shape shape_15;
	Shape shape_16;
	Shape shape_17;
	Shape shape_18;
	Shape shape_19;

	_Player_Head() {
		// Calque 3
		shape = _draw(-9.8,17.3)
		.f(0xFFCF764B).s().p("Ag8AAIAEgJIAAAAIAIgVQAIgHAGgMIALgXQAKA3AkAvQAOASAYAYQgwghhJgng").shape;

		shape_1 = _draw(-16.9,-2.4)
		.f(0xFF3C003C).s().p("AhBBWIgngmQgNgNgEgNQgCgNAAggQAAgvATgrQALgWASgeIgSBZQAAAnALAOQANAJAIAHQAFgTAhguQAfguANgIQgOAdgSA4QgSAzAAAIQAAANAGALQAIANAOAAQACAAAegkIBehuQgoA5hNDBIgDAHQgjgugjgig").shape;

		shape_2 = _draw(-4.4,-8.1)
		.f(0xFF2B002B).s().p("AjcCDQgvgzAAgvQAAiYBrhHQBPg2B2AAQBBAABCAVQBMAZAYAnIAAABIgyAJIgkAGIgDABIgZAGIgSAGIgVAJIgYAOIgKAHIgLAJIgOANQgVAYgLAPQgOATgYAtIgHAMIgIAQIgMAWIgFAMIgaA4QgHARgXBAIgIAUIAAABQgqgxhEhBgAhjjMQg4AbgtBFQgRAegLAWQgUArAAAtQAAAiADANQADANANANIAoAmQAiAiAmAuIACgHQBNjDAmg3QAegsBRguQBZgyAxAMQhwhDhbAAQhcAAg1AZg").shape;

		shape_3 = _draw(-2.9,-14)
		.lf([0xFF3C003C,0xFF970198],[0,1],-33.1,12.6,1.2,-21.7).s().p("AiiCeQgHgLAAgNQAAgIATg1QATg4APgbQgOAIghAsQghAugFATQgHgHgOgJQgKgOAAgnIARhXQAthFA3gbQA2gZBcAAQBbAABvBDQgwgMhZAyQhRAugcAqIhdBwQgfAkgEAAQgOAAgHgNg").shape;

		shape_4 = _draw(22.6,-19.8)
		.f(0xFFFFDF62).s().p("AA1CBQgeg1g1geQhDgdgjgSIgFgEQAcAFATADIATAGIgkgZIADAAQAKAABiAQQAIABAKAAQBFAAAmgjIAJgHIgKAgQgXAZgTAKQgUALgZAAQgfAAgWgEIASAKIAYATQgIgCgBACIAWAmQATAjABAGgAgygRIglgJIAkgGIAJACIAQACQAgAAAXgRIAIgHQgLANgKAIQgTAQgfAAQgIAAgIgCgABDgzQAEgMAAgHQAAgYgDgDIgPAXQAKgTACgdIACgSQAKAgAAAOQAAAJgCARQgFAZgHAQg").shape;

		shape_5 = _draw(-0.1,-0.2)
		.f(0xFFCCCCCC).s().p("AAAAAIAAAAIAAAAg").shape;

		shape_6 = _draw(-1.5,-3.3)
		.f(0xFF53D5FF).s().p("AAAAAIAAAAIAAAAg").shape;

		shape_7 = _draw(8.9,15.3)
		.f(0xFFFFFFFF).s().p("AgiABQgNgUgFgCIABAAQAJAHAdAHQAiAIAggBQgCAGgFAEIgGAFIgBABQgLAGgPAAQgdAAgSgVg").shape;

		shape_8 = _draw(7.8,13.2)
		.f(0xFF070609).s().p("AgmAPIgSgfQAUAPAkAEIAxAGQAZADAGAJQgJACgNAJQAFgFABgGQgfACgigLQgdgHgKgFIAAAAQAFAAANAWQASAWAcAAQAPAAALgHIACgBIgDADQgSANgIAAQgkAAgZglgAhPgyIABgBIAAABIgBAAg").shape;

		shape_9 = _draw(15.3,9.9)
		.f(0xFFF4AD82).s().p("AhgBcIgNgMIgBgCIgBgHQAAgGABAAQABABAAAAQABAAAAAAQAAAAAAAAQABAAAAgBIAeAQQAEADABAKIgHABQgHAAgKgDgAgBhSIAQgLIACgBQAEADAtAVQApASAFAJIgUACQg1AAgogpg").shape;

		shape_10 = _draw(12.3,-0.5)
		.f(0xFF0098CA).s().p("AhXAfIA3gxQAVAAANAKQAPAJAAAPQgcAQgMAFQgKAEgLAAQgOAAgdgKgABaATQgIgBgOgGIgMgHQAKgFAzgLQAGAAACABIABACIAAACQAAAJgLAIQgKAIgOAAIgBAAgAh3ghQAHgHAIAAQAGAAAFACIAJAEIgnAlQgHgYALgMg").shape;

		shape_11 = _draw(11.9,-2.8)
		.f(0xFF33CCFF).s().p("AAGANQgNgKgVAAQACgBADgFQAEgHAFAAQAeAAAXAJQAMACAGAEIBOgKQAAAGgFAMIgBgCQgCgBgGAAQgyALgLAHIgEgEIgDABIggAOQABgPgQgLgAh3AaQgKgPgEgOIABgBQABgQAJgKQAHgIAJAAIARAEIAXAHIgOAQIgIgEQgGgCgGAAQgIAAgGAHQgLAKAGAag").shape;

		shape_12 = _draw(11.7,-2.2)
		.f(0xFF006F93).s().p("AhzAlQgegeAAgkQAAgSAGgJQAIgKAQAAQAlAABJAYQAiALAeAMQAUAAAegEIAAgCIAKgBQAOAAAJABIADALQADAKgMATQgLAUgJAHIACAAIgXgGQAQAAAKgIQALgIAAgLIAAgCQAEgKAAgIQgMgGgMADQgWAGgbAAQgPAAhCgXQhDgYgcAAQgKAAgHACQgDATAAAHQAAAKABAHIAAABQAFAOAKAPIAAAAQALAQAZAMQAdAKAOAAQALAAAKgEQAMgFAcgQIAggOIgEAIIgSALQgIAFgdAMQggAMgFAAQgrAAgfgeg").shape;

		shape_13 = _draw(11.8,-2.6)
		.f(0xFFAEEBFF).s().p("Ah2AYIAAAAIAngmIAOgPIgYgHIgQgEQgJAAgIAIQgIAJgCARIgBAAQgBgHAAgKQAAgHADgUQAHgBAKAAQAcAABDAYQBCAWAPAAQAbABAWgGQAMgEAMAHIhNAJQgGgCgMgEQgXgIgeAAQgGAAgEAGQgDAGgBAAIg3A0QgZgMgLgQg").shape;

		shape_14 = _draw(8,5.3)
		.f(0xFFF19761).s().p("Ag8DEQglgPgZgVQgcgrgSg0QgQgtAAgXQAAgFANgmQAOATAEAMQACAHAAALQAAAJgCAFIACABQALgNAIgSQAHgUAAgRQgHgqgHgQQAbgvANgTQALgPAVgYQAnAFAiAHQgNACgbAOQgYAMgFAFIAFgDIgIAIIgCACIAGABIAsgNQArgMAOACIARAKIABAAQgCgFgFgIIBXAyQAHAVACANIAAADQgeAEgUAAQgegMgkgLQhHgYglAAQgQAAgIAKQgGAJAAASQAAAmAeAeQAfAeArAAQAEAAAfgMQAfgMAIgFQAxAuBBgJQABAKgKAOQgLAHgeAJQgeAJgHAAIgPgCIgWgDQAEANAWARQAVAPAKAAIgfBWQgTAmgmAAQgqAAgvgSgAgeCUQAOAKAVAAQANAAAHgDQAGgDAHgJQgJADgXgDQgVgCgIgDQAQAFAHgDQAAgKgFgDIgdgQQAAAAgBABQAAAAAAAAQAAAAgBAAQAAgBgBAAQgBAAAAAGIABAHIgJgKQAAAWAQAMgAgoBfQAZAkAkAAQAIAAASgNIADgDIAGgEQANgJAJgCQgGgIgZgEIgxgGQgkgGgUgPIASAigAhRAbIABABIAAgCg").shape;

		shape_15 = _draw(6.7,6.7)
		.f(0xFF552D17).s().p("AAyDYIhLgBIgXgGIABgCQgjgLgUgRQgZgZgOgSQglgxgLg2IgKAWQgHAMgHAHQAWg/AHgPQACAWANAmQAWA9AmAdQAZAVAlAPQAvASAqAAQAmAAATgmIAfhWIAKgXQgYAAgMgDIgJgEIgJgHQARAGAPAAQALAAAVgIQAZgLANgPQAKgMgBgKQgFgJgpgSQgsgVgEgDIgCABIAEgIIADgBIAEAEIAMAHQAOAGAIAAIAWAHQAVAIANAJQAMAJAAAGQAAAXgJAMQgEAGgSANQgnAbgSBDQgLAsgFALQgHASgNAGQgJADgVAAIgKAAgACWiWIgIgSQgMACgBgDQADgGAFgDIgEgFIAZARIALAyIgKAAQgCgNgHgVgAgVjHQAZgOAPgCQAigDAKASQAFAIACAFIgBAAIgRgKQgVgFgKAAQgdAAgQAGIgVALIgFADQAFgFAYgMg").shape;

		shape_16 = _draw(6.9,1.9)
		.f(0xFFCD784B).s().p("AirBoQgNgmgCgYIAag3IAAABQgNAjABAGQAAAZAPAsQASA0AdAsQgngegWg8gAgSC1QgQgLgBgWIAJAJIABACIANAMQAJAEAUACQAXACAJgDQgHAJgGADQgHADgNAAQgUAAgOgKgABhBsQgWgQgEgOIAWAEIAPABQAHAAAegJQAegJAMgGQgNAPgaAKQgUAIgMAAQgPAAgQgFIAJAGIAJAEQALADAZAAIgLAYQgJAAgWgQgAA9iYQgKgTgiAEQgigIgngFIAOgNQAPAABBAVQBBAUAMAHIARAKIADAFQgFADgDAFQABAEANgDIAIATIhYgygAg4h/IABgCIAJgIIAUgMQARgGAcAAQAKAAAVAGQgOgCgrAMIgsAMIgFAAg").shape;

		shape_17 = _draw(12.4,-10)
		.f(0xFFDDB000).s().p("Ai9CVQABgNgFgQQgGgSgKgJIALgWQAAAFAHAZQAHAWgEAbgAAWg1QhAgbgrgCIAJgHQAhgBA2AWQA8AYAeAfQgbgTg0gVgACMgYQgFgJgCgBIgZgUIAbAIQANADAGAAQALABAtgXQgGAMgOAPQgVAVgUAAQgFAAgEgHgAAKhdQgQgFgdgFIAGADIgWgDIAUgJQASAGAVAJIAVAKIgTgGgAgBhzIgLgDIAWgGQBAAWAQAAQALgBAYgKQAfgQAOgUIgFAXQAFAMgDAEQgEAGg5AFIABABQhlgQgHgBg").shape;

		shape_18 = _draw(14,-12.3)
		.f(0xFFFFCC00).s().p("AjMCtQAFgbgHgWQgIgZAAgEIAJgQIAHAaIAFAUQAAAIgEAQQgCAQgEAIgABVAIQgegdg6gYQg4gWggACIAYgPIAWAEQAjAUBAAdQA3AcAfA1Ig3gugAB3gXIgbgHIgUgKQAYAEAgAAQAZAAATgLQAUgKAXgbQgMAfgIAMQguAWgLAAQgGAAgNgEgAgGhJQgWgKgTgGIATgGIALAEIgDAAIAiAbIgUgJgAgEhkIAEgBIAjAJQAHACAJAAQAfAAAVgQQAKgIALgNQAJgJAHgNIAOgXQADADABAYQAAAHgEAMQgNAVggAPQgYALgLAAQgQAAg+gVg").shape;

		shape_19 = _draw(14.6,-14.8)
		.f(0xFF796100).s().p("AjbDbQACgFAAgKQAAgMgCgHQgEgNgOgSIAAgBIAFgMQALAKAGARQAFARgBANIABAAIABAAQADgIADgQQAEgQAAgIIgFgUIgIgaIAHgMQAHAQAHApQAAASgHAUQgIAUgLAMgACSBpQgYgbgrgfIgZgQIgQgKQgMgHg/gSQhDgVgPAAIAMgJQArACBAAbQA0AUAbASIA2AuIALAMQgCgGgTgjIgVgmQABgCAIACQACACAFAIQAEAHAFAAQAUAAAVgVQAOgNAGgLQAIgMANgfIAKggIgKAHQgmAlhFAAQgKAAgHgDIgBAAQA5gGAEgGQADgEgFgLQAIgQAEgZQADgRAAgJQAAgOgLggIgBASQgDAdgKATQgGANgJAJIgJAHQgXARghAAIgRgCIgJgCIAygKIAAAAQAQgGAVgdQAcgkAAglQAAgJgDgJIACACQAZAzAAASQAAANgDAYQgEAagEAOQAogSApgcQAMAoguA3QgpAvggAGQAIAOAHASQAKAZAAANIAAAIIgCACg").shape;

		addChild(shape_19);
		addChild(shape_18);
		addChild(shape_17);
		addChild(shape_16);
		addChild(shape_15);
		addChild(shape_14);
		addChild(shape_13);
		addChild(shape_12);
		addChild(shape_11);
		addChild(shape_10);
		addChild(shape_9);
		addChild(shape_8);
		addChild(shape_7);
		addChild(shape_6);
		addChild(shape_5);
		addChild(shape_4);
		addChild(shape_3);
		addChild(shape_2);
		addChild(shape_1);
		addChild(shape);
	}
}

class _Player_Forearm_Left extends Sprite {
	Shape shape;
	Shape shape_1;
	Shape shape_2;
	Shape shape_3;
	Shape shape_4;
	Shape shape_5;
	Shape shape_6;

	_Player_Forearm_Left() {
		// Calque 1
		shape = _draw(38.1,9.9)
		.lf([0xFF980101,0xFFFD1C1C],[0,1],-5.4,-12.6,17.2,-9.4).s().p("AAABRIgEgFQAAgGACgFIADgJIAPAHIAOAGQgHADgCAEIgGAPQgLgFgEgFgAgoBEQgJgLAGguQgMgIgHAAQgMgCgNAYQAGgUABgVQApAKAFgiQADgWACgFQAGgPARgDQgNAMgDAZQgBAPABAeIgxgCIAGACIAfAHIAPgFQAHAKAKAHQAHAGAAACQAAAEgYAzQgPgEgGgHgAAIA4QgIgEAAgFQABgFAKgDQAKgFAPgBQAPgBADABQgIAPgEAPQgagCgIgFgAASARIAGgNQAHgNAGgTIAiACQgGANgCANIgCARIABAIQgogCgEgGgAgOgeQAAgKACgNQAEgZAIgMIANABQAFADAAAMQAAAWgKANQgJAMAAAIQAAADACAIQAFAIAIAFIgHABQgVAAAAgkgAAogkQAKgkACgPQgBgCAHAAIAGABQgCAIgCASIgDAWQANAFASACg").shape;

		shape_1 = _draw(39.6,8.5)
		.f(0xFFEC1717).s().p("AAABoIAGgPQACgDAHgEQAPADAcAAQgKAMgRAGQgJACgJAAQgHAAgGgBgAhWBZQgVgKAAgWIABgFIABgIIACgFIAAgBQANgYANACQAHABALAHQgFAuAJALQAFAHAQAEQgMACgLAAQgRAAgMgFgAAmAuQAFAAAMgEQANgCANAMQgFAKgTAHQgQAGgOABQAEgPAHgPgAAvAmIgBgIIACgRQABgNAGgMQAbABANAJQANAHgEALQgEALgSAGQgOAFgPAAIgGAAgAgMADQgEgFAAgDQAAgJAKgMQAJgNAAgWQAAgMgDgCIgOgBIAAgBIgHAFQgSADgGAPQgCAFgDAWQgEAggpgIQADgcAcgiQAggnAhAAQAaAOAAATQAAAUgMAiQgLAdgEAHQgHgGgFgKgAAqgbIACgVQACgTACgIQAmAJAIAEIABAAQAFADADAEQAFAGAAAJQAAANgHADIgcAEQgTgCgMgFg").shape;

		shape_2 = _draw(37.4,8.6)
		.f(0xFF2D080A).s().p("AhEBdQhFgTgBgIIACgKQADgiAFgTIAAANQAAAYAHARQAHARAKAAQAKAAAIgRIACgFIgBAFQAAAWAVAJQATAJAhgFQAXgzAAgEQAAgCgIgGQgJgHgHgMIgOAHIgggJIgGgDIAxADQAAgcABgPQACgZANgNIAGgFIAAABQgIAMgEAZQgCAMAAALQAAAqAcgHQAGgHALgcQAMgjAAgTQAAgTgagPQghAAggAoQgcAigDAcQgBAVgHAUIAAAAQACgKAAgMQAAgWgHgSQgIgRgKAAQgHAAgGAJIACgJIACgKIAlAJQACgOAfgaQAigfAbAAQBFAdAeAWIgBAAQgIgEgmgJIgGgBQgGAAAAACQgBAPgLAkIAxADIAcgEQAHgDAAgNQAAgJgFgHQAOANAAAKIgGAmQAAAZghAqQghAqgSAAQgtAAhIgVgAADBNQgDAFAAAHIAFAFQAGAFALAEQAOAEARgFQARgFAKgMQgcAAgPgDIgOgGIgPgIIgFAJgAAqAuQgPABgKAEQgKAEgBAFQAAAFAIAEQAJAEAaADQAOgBAQgGQATgIAFgKQgNgMgNACQgMAFgFAAIgFgBIgNABgAAeARIgGANQAEAGApACQASABARgGQASgHAEgKQAEgLgNgHQgNgJgbgCIgigCQgFARgIAPg").shape;

		shape_3 = _draw(8.7,4.3)
		.lf([0xFFF19761,0xFFB9623E],[0,1],9.2,-7.2,-8.6,2.2).s().p("AhnAzQgpgfAAhBQAAgOADgIQAXgKAbgCQgYAOgNAQIAkgQQAfgOASgBQAlABAoAgQAyAoA8ANQgGANgBgCQgDAOgNApIhlAIQhTAAgogdg").shape;

		shape_4 = _draw(8.8,6)
		.f(0xFFBA643F).s().p("Ah7A0QgkgbgHhAIANgoIALgGQgDAJAAAOQAABBApAeQAoAeBTAAIBlgIQANgqADgNQABACAGgLIAYAGIABAAIgLAgQgFATgDAiIh1AEQhuAAgtgig").shape;

		shape_5 = _draw(26.9,10.2)
		.f(0xFF112635).s().p("AgQApQgHgSAAgXIAAgLIALgjIAAgCQAGgJAGAAQAKAAAHARQAHASAAAWQAAAMgCAKIgCAFIgBAIIgCAGQgHARgKAAQgJAAgHgRg").shape;

		shape_6 = _draw(8.2,5.3)
		.f(0xFF552D17).s().p("AhdBcQhRgaAAhMQAAgLAHgSQAIgVAMgMIgOAoQAIBAAkAbQAtAiBuAAIB1gEIgDAKQhIAHg3AAQhKAAgsgOgACsACIgXgEQg8gPgzgoQgnghglAAQgSAAggAOIgkARQAOgQAXgOQAJgGAIgDQAOgHAWAAQAQAABQAtQBYAvAZAFIgBAIIgBACIgBAAg").shape;

		addChild(shape_6);
		addChild(shape_5);
		addChild(shape_4);
		addChild(shape_3);
		addChild(shape_2);
		addChild(shape_1);
		addChild(shape);
	}
}

class _Player_Forearm extends Sprite {
	Shape shape;
	Shape shape_1;
	Shape shape_2;
	Shape shape_3;
	Shape shape_4;
	Shape shape_5;
	Shape shape_6;

	_Player_Forearm() {
		// Calque 1
		shape = _draw(41.7,21.3)
		.lf([0xFF980101,0xFFFD1C1C],[0,1],10.1,10.2,0.1,-5).s().p("AhQA9IgVgmQAAgQAPgdQATgoAcgTIBWgQQACAAAMAJQANAKAIALIAAADQAGADgKAAQgDAAgQgIQgRgIgFgCIgQgBQAGANAsAhQAiAbgDAdQgJANgFADIgGADIgjAgQgPAGgSALQgMAIgHAAQgsAAgfglg").shape;

		shape_1 = _draw(10.8,7.4)
		.lf([0xFFF19761,0xFFB9623E],[0,1],11.4,-4,1.3,10).s().p("Ag8AgQg5ghgngSQgFgFgMgpQACgCAYgRQAYgPAcgEIgGACIAIgCQAagEASAAQBAAAAlAdIB6B0QgFAGgQAeQgQAdgCAFQiBgohCgkgAh1ghQAGAJA/AYQA4AUA0AOQgjgUgigRQhHgjgegCIgHAHg").shape;

		shape_2 = _draw(43.2,22.9)
		.f(0xFF9C0202).s().p("AhVA5QgqglAAgJQAAgaAggqQAcgmANgCQgcATgTAoQgPAfAAAOIAVAmQAfAlAsAAQAJAAALgHQARgMAPgGQgTAPgMAHIABADQAVgDAegZQAQgNANgNIAIgEQgEAPgfAbQgmAggfAAQgZAAgugpgABgAVQALgSAAgFQAAgGgBgCIgEgGQgFgGgCgGQABAIgCALQgDAJgEAGQADgcgigbQgsgigGgNIAQACQAFABARAJQAQAHADABQAKAAgGgEIAAgDIAVAgIg1ghIgEgCQAUAfApAYQAkAUAAAFQAAAfgdAAg").shape;

		shape_3 = _draw(9.7,11.1)
		.f(0xFFBA643F).s().p("AgaAWQhZgmgegoQAnARA5AjQBCAiCBAoIgCAIQhXgRhTgngAglgmQg/gYgGgJIAHgGQAeABBFAkQAkASAjAUQg0gOg4gWg").shape;

		shape_4 = _draw(30.2,17)
		.f(0xFF112635).s().p("AgoBBIgJgCQgCgBAAgHIAAgDQAAgnAZgoQAYgnAQABIAKAFQANAIAPAMQguA5gIAUQgGANAAARQgWgBgKgBg").shape;

		shape_5 = _draw(40.5,21.5)
		.f(0xFF070609).s().p("AhLBEQgtgegXgTQALACAVAAQAAgRAGgLQAKgUAvg7QgQgMgNgIIgJgFQgTAAgYAnQgZAqAAAlIAAACQgIgIgCgDIACgWIACgIQACgFAQgdQARgeAEgGIAOgOQATgBAdAOIAbAOQAFAAArgKQAtgJAEAAQBkBfAAAWQAAALgHALQgIANgNAAQgLAAgLAMIgVAZQghAkgyAAQgLAAhLgxgAgahTQgNACgdAmQgfApAAAbQAAAIAqAmQAtApAYAAQAgAAAmggQAggbAEgPIgJADQgNAOgPANQgfAZgUACIgBgCQALgHAUgPIAiggIAGgDQAGgDAJgNQAEgGACgLQACgJgBgIQADAGAFAGIAEAEQABACAAAGQAAAHgMASIAEAEQAcgBAAghQAAgEgjgSQgqgYgUggIAEADIA2AhIgVggQgIgLgOgKQgLgJgCAAg").shape;

		shape_6 = _draw(11.4,8)
		.f(0xFF552D17).s().p("AhaA3QhUg3gHgoIADgfQAMApAFAFQAdAmBaApQBTAnBWARIgCAVQh2gKhhhCgAAvhVQglgchAAAQgSAAgaAEIgIACIAGgCQAbgIASgIQAJgFAUAAQBAAAA5A3QAhAfA2A+IgNAOIh6h1g").shape;

		addChild(shape_6);
		addChild(shape_5);
		addChild(shape_4);
		addChild(shape_3);
		addChild(shape_2);
		addChild(shape_1);
		addChild(shape);
	}
}

class _Player_Chest_3 extends Sprite {
	Shape shape;
	Shape shape_1;
	Shape shape_2;
	Shape shape_3;
	Shape shape_4;

	_Player_Chest_3() {
		// Calque 1
		shape = _draw(1.8,-45.3)
		.f(0xFF1291C7).s().p("AhLCyQhbAAgZgMIAEgQQDjAKAqADIArADIAAAOQg4gDiQABgABVCVIAehiQAchbACgKIAKgfIAKgDQAMgDAMgCQg+DhgCAVgACeizIAiAAQgEAMAAAIIglAGg").shape;

		shape_1 = _draw(1.3,-62.4)
		.f(0xFF15ABEA).s().p("AgUF+QiFgDgrgJIAKghQAaAMBbAAQCQgBA3ADQAAAHADAZIiZgBgACcAQIAlgHQADAOABAWQAAAWgDANQgMACgLADIgKADQAEgogJgggACWh6QgGgTgRgmQgZg6gegiIAbgRIAAAAQBDBiAYAwQAWArAAAjQgEAqgKANIgjABQgGhXgHgbgAjKldIgJghQB1ADA1AHQBdAJBGAbIgPAWQi7gnh6AEg").shape;

		shape_2 = _draw(-3.6,-49.4)
		.lf([0xFF030118,0xFF0D023E],[0,1],-58.3,97.9,-75.7,67.8).s().p("AiBHAQgrgeAAhDQAAgXAKgkQAFgUALggQArAKCCACICbABIAGBXQAABfg/AeQgeAPhFAAQhsAAgvgggAgKC6QhWgBgggCQgFgIgHghIAAgLQAAg9gOgtQgFgPgJgTQgShRgahhQARAMADAAQAgAAAEgiIAGhJQAYhrDZgBQgOgJg1gTQg/gXghAAQhBAAgoAtIAjgvIgLgkQB6gDC8AnIgMAWIACADIABABIgbAQQAfAiAZA6QgFgDg4gOQg2gOgIAAQgQAAgKAOQgLAOAAAaQAAA8AzArQA4AwBZgDIgHAaQhagFgZALQgSAHAAAeQAAATASAQQAUAQAbAAQAIAAAbgIQAbgIAKgGIgKAfQgjAKgdA8QgcA6gFBEIhxgBg").shape;

		shape_3 = _draw(-4,-62)
		.f(0xFF180479).s().p("ABrE5QAFhDAcg7QAdg8AjgMQgCAKgcBdIgeBigABfBaQgSgQAAgTQAAgeASgHQAZgLBaAFQAIAggEAoQgKAGgbAIQgbAJgIAAQgbAAgUgRgABIg4QgzgsAAg8QAAgZALgPQAKgOAQAAQAIAAA2AOQA4AOAFADQARAmAFAUQAHAbAHBXIgLAAQhRAAg1gtgAjQg9QgDgLgCgXIgDgdQAAgaAQgyQAMgmALgXIAEgJQAogtBBAAQAhAAA/AXQA1AUAOAJQjZAAgYBrIgGBKQgEAhggAAQgDAAgRgMg").shape;

		shape_4 = _draw(-1.5,-47.9)
		.f(0xFF0B0233).s().p("AiQHjQhCg+AAhVQAAgXAZhOQAWhEACgnQAHAgAGAJQAgABBVABIByACIAlACIAoAIQABgUA+jhQADgNAAgWQgBgWgDgOQAAgHAFgNQAKgOAEgqQAAgigWgrQgYgxhEhhIAAgBIgDgDIAMgWIAPgWQhHgbhcgKQg1gGh1gDIAJAhIALAkIgkAuQAagzAAgDQAAgUgIgOQgKgVgDgNIBDgCQA6AAA/AIQBqAMA/AfQgfAwAAABQAeAnAfAuQA8BcAAAnQAAAzgKAYIgLAPQAAAFAEALQAEALAAAFQAAAfghBeQgiBfAAA3IAICcQAABVgfA0QggAzhjAMQgRACgNAAQhPAAg3g1gAidDBIgKAhQgKAggFAUQgKAkAAAXQAABDArAdQAuAgBsAAQBFAAAfgPQA/geAAhfIgHhWQgCgZAAgHIABgOIgsgEQgqgDjigKgAjOg5QgvhWAAhoQAAg1AphRIAKgVQgLAYgLAlQgQAzAAAZIACAeQADAWADAMQAaBhARBRIgRgig").shape;

		addChild(shape_4);
		addChild(shape_3);
		addChild(shape_2);
		addChild(shape_1);
		addChild(shape);
	}
}

class _Player_Chest_2 extends Sprite {
	Shape shape;
	Shape shape_1;
	Shape shape_2;
	Shape shape_3;

	_Player_Chest_2() {
		// Calque 1
		shape = _draw(14.8,-44.1)
		.f(0xFF1291C7).s().p("AhaCUQALgTA6hNQA+haAyhuQAAANgOAxQgRA5gQAdQgDAHgbAmQgaApgfA+g").shape;

		shape_1 = _draw(-2.2,-61.8)
		.f(0xFF15ABEA).s().p("AiEF9QgOgEgMgGQABgIAIgOQAIgMABABICUADQCQAEANgCIgBAnQh5AFgSAAQiCABgbgHgACok+QgmgOhNgLQhkgPh6AAQAAgGgEgVIBLgCQA+AEA5AFIARABQBKAIAhAIQAdAHAAAJQAAAHgGAUg").shape;

		shape_2 = _draw(-3.9,-46.5)
		.lf([0xFF030118,0xFF0D023E],[0,1],-58.1,95.1,-75.5,64.9).s().p("AhjHpQhdhVABhUQAAgLAchPQAchOAAgVQABg3gZg1QgMgZgqhAQgmg7gQgoQgYg+AAhHQAAg7AZg0QAmhJBHACQgEgLgGgXIgEgWQAAgOAaAAQBtALBKAIQg5gFg+gDIhLACQAEAUAAAHQB6AABkAOQBNALAmAOIAAAAQAGgUAAgHQAAgIgdgHQAfAFAMAFQgJAtgFAMIgCAGQAaApAaAuQA0BcAAAgQgBASgJAUQgLAVAAAMQAAAGAEAOIADAPQgyBthABaQg6BNgLAUIAuAAQAgg/AcgoQAbgmADgIQgaBcgPBqQgKBogHAmQgKA9gPAqQgPAqhHAgQgUAKgVAAQg2AAhDg+gAiEDFQgIANgBAIQAMAHAOADQAbAHCCAAQASAAB5gGIABgmQgNABiQgEIiUgDQgBAAgIAMgAA1iLQg8A8gJA0QAnAGBYg3QBcg6AAguQAAgJgQgPQgOgPgOgGQhbBIgPAOgAhKmVQg6A5gBBlQABB7AuAAQBTAABRhjQBJhYABg6QgBhWhqAAQhEAAgzAygAkEi4QA3AoAFgBIAEgCQABgLgGhjQAAhvAehJIgKgOQg1AcgYAuQgVApAAA8QAAA2ASAnQASArgSgqg").shape;

		shape_3 = _draw(-7.7,-70.8)
		.f(0xFF180479).s().p("AAVDVQAJg0A+g7QAPgOBahJQAPAHAOAOQAPAPAAAKQABAthdA6QhOAygpAAIgJgBgAhegEQAAhlA6g6QAxgxBHAAQBqAAAABWQAAA5hKBXQhTBihQAAQgvAAAAh4gAjdA4IgCgCQATArgTgrQgRgngBg0QABg8AVgpQAXguA1gdIAKAPQgdBJgBBvQAHBhgBAKIgFACIAAAAQgGAAg1gng").shape;

		addChild(shape_3);
		addChild(shape_2);
		addChild(shape_1);
		addChild(shape);
	}
}

class _Player_Chest extends Sprite {
	Shape shape;
	Shape shape_1;
	Shape shape_2;
	Shape shape_3;
	Shape shape_4;
	Shape shape_5;
	Shape shape_6;
	Shape shape_7;
	Shape shape_8;

	_Player_Chest() {
		// Calque 1
		shape = _draw(-0.3,-46.8)
		.f(0xFF1291C7).s().p("AhDDIIhpgHIADgIIE3AAIAEAPIg2AEIgvABQgUAAhcgFgABcCuIALAAQgDgRgDgcIgCgjQAAgmAQiAIAIgcIAzgGIgRBqQgQBhAAAlIADAnIgwACQgJAAAJgBgAB6i7IAGgRIAoADQADAIACAIg").shape;

		shape_1 = _draw(-1.5,-62.8)
		.f(0xFF15ABEA).s().p("AixGCQAIgIAJgZIBoAHQBcAFAVAAIAvgBIA1gEIAHANIAGAPQgCAAgEgDQAAgBgBAAQAAAAAAABQgBAAAAABQAAABAAABQAAAHg9ACIhFABQhSAAh/gMgACHgJIgCgPIABgDIAyACQAEApgGAkIgzAGQAIgrgEgYgACMgsQgBgmhBg/IhRhOIgGgUIgFgQQAAgJAogHIAFAJQA2A0AiArQBCBPgBAzgACEkAQgfgvgJgHIgHgZQgFgWgBgOQgCgZgCAAIAcgBQAJAAAXAEQAaAFAQAFIgdA6QgJARAAACQAAANAfBbQgGgGgggwgAg6lVIgvgDIhFACIgKgeQA2gFAiAAQBHAAAYAQQAMAKgCAQQgYgDgrgDg").shape;

		shape_2 = _draw(-4.2,-98.6)
		.f(0xFF552D17).s().p("ABpgTIABAGQABANAFAUIAIAaIgKAKIgFhLgAh3geIAQgWIACgCQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAAAAAIAAgBIACABQAEADgEAHQgEAJABAEIgSABQgBAAAAAAg").shape;

		shape_3 = _draw(10.1,-82.6)
		.f(0xFFCCCCCC).s().p("AAUAVQhCg8gbgiQAIgBATgJQAUgJAEgGQAuAzASAkQAVAmALBJQgKgngsgog").shape;

		shape_4 = _draw(-3.8,-100.4)
		.f(0xFFBA643F).s().p("AAuA9IgEg9QgTAAg9gHQg4gHgKACIAAAAQgBgEAEgJQAEgIgEgDQgBgDAEgGIAHgHIAggYQAfgUAVAAQAvABAWAKIAYATIAJAWIAAAIQADAbADAJIAFBLQgLAKgMAHQgIAFgDAAQgUAAgGgkg").shape;

		shape_5 = _draw(-4.5,-49.7)
		.lf([0xFF030118,0xFF0D023E],[0,1],-57.5,98.3,-74.9,68.1).s().p("AiAG5QglgbAAhEQABgwAUgOQARgKAxAEQBkAIAJABQBTACBQgQQAGArAAAdQAABQgvAdQghAWhEAAQiEgBgwgigAh8DNQACgIACgeIADglQAAgugMgYQgRgfgBgDIALAEQhOhfgbgyQgfg9gBhEQABhVA4g3QAcgcAdgLQAegWA1AFQgkgEgaACQABgDgCgKQgCgLgDgHIBFgBIAvACQApADAaAEQAAAFAGAYIAHAeQgqAHAAAJIAEAQIAHAUQgSgEgYgDQgSgCgMAAQggAAgVAUQgVATAAAXQALA9APATQAUAzBAANQA4ANB7gOIgQgBQgNgCAAgGQAAgGgFgBIAngBIgFARIgBADIACAPQhWAMhgADQgWAAgFADQgGADABAKQAAAZAZAhQAYAhAYAAQAUAAA0gXIBAgeIgIAdQg6APgtAgQgmAeAAASQAJBGAAALIgHBGIhjACIgmgBgADfgxQAHgWAAgHQAfAEANAGIgMAbgADjiqQAJg0AAgcQAAgogahIIgbhGIAIgPIACABIAHAEIAFAEQAMAHALAYIgBAHQADApACALQAEALAHAAQACABAGAUQAGAcAAAmIgMBFQAAAHACAEIADACg").shape;

		shape_6 = _draw(20.9,-74.6)
		.f(0xFF0D023E).s().p("AgSBwQgCgPgGgVIAYACQAWAAAFgBIgBAPQAAAGABAFIACAOgAAChwIgCgEIAAABIACADgAAFhyIACABIgBAAIgBgBg").shape;

		shape_7 = _draw(4.1,-59.9)
		.f(0xFF180479).s().p("AhADrQAAgKgJhGQAAgTAmgdQArgiA6gQQgPCCAAAmIACAjQADAcADARIiCABgAB0C6QANhiAIglIAnAIQgaAvgWBGQgQA4gKA7IAOhpgAhuAwQgZggAAgXQgBgKAGgDQAFgDAWAAQBigEBUgLQAEAagJApIhAAdQgyAYgUAAQgZAAgZgigACQAWQAFgdgBgZIAvAEQAAAigHAaQgNgGgfgEgACihFQgDgDAAgHIAMhGQAAglgGgcQgGgVgCAAQgHAAgEgLQgCgLgDgpIABgHIANAXIgEgIIALARIAHALIgBgBIACAEIABAAIAMAXQAdA2AAArQgBAQgGAYQgGATgGAMQgFACgYAAgAhahUQhKgMgVgYQgPgSgLg9QAAgXAVgTQAVgUAgAAQAMAAASACQAaACASAFIBQBOQBCA/AAAmIgnABQgFgCgJACQhQgFgogHg").shape;

		shape_8 = _draw(-3.5,-48.4)
		.f(0xFF0B0233).s().p("AiAH0QhEhIAAhVQAAhVAcgmQAbglAAhDQAAgfgZgxQgKgUguhKQhRiGAAhPQAAhcApgoQASgRBRglIgRhEIA1gGIATgBIAAAAQAKgCA4AHQA9AHATAAIAEA/QAGAkAUAAQADAAAIgFQAMgHALgKIAKgKQAJAHAeAuQAhAwAGAHQgfhcAAgMQAAgDAIgQIAeg7QgQgFgagEQgXgEgJAAIgdAAQACAAADAaIgCgGQgDgJgDgbIABADQA7gFAmAJQAdAHAAAHIgQAZQgPAXAAAQQAAAIADAJIgHgFIgCgBIgIAPIAbBHQAaBHAAAoQAAAcgJA0QAFAVACAPQABAZgFAfQAAAIgHAWQgIAlgNBfIgOBqQAKg8AQg3QAWhFAaguIAMgcQAHgaAAgjIgBgOQgCgFAAgHIABgOQAGgNAGgTQAGgXABgQQAAgsgdg1IgMgXIgCgEIgHgLIAIAJIADAEIABABQA2A+AAA4QAAAOgMAfQgMAfAAAPQAAAyguCSIgvCVIANBDQgBALAEAgQAEAgAAAKQgBBbgmA3QgnA3hfAUQgUAEgSAAQhGAAg2g5gAiaEQQgUANgBAwQAABEAlAbQAwAjCEAAQBEAAAhgVQAvgeAAhPQAAgegGgrQhQAQhTgCQgJAAhkgJIgYgCQgdAAgNAJgAiMDRQgKAZgHAIQB/AMBSAAIBFgBQA9gCAAgGQAAgCAAgBQAAgBAAAAQABgBAAABQABAAAAAAQAEAEACAAIgHgPIgGgNIgDgQIk4AAgAiLAwQAMAXAAAvIgDAkQgCAegCAIQAdADBsgEICEgBIgMABQgJAAAJABIAxgCIgEgoQAAglAQhjIAShoQAGgjgEgrQgBgJgDgIQABgyhChQQgigqg2g0IgFgKIgHgdQgGgYAAgGQABgRgOgJQgVgQhHAAQgiAAg3AEIALAeQADAIACAKQACAKgBAEQAagDAkAEQg1gEgeAVQgdAMgcAbQg4A3gBBVQABBEAfA9QAbAzBOBfIgLgFQABAEARAfgABYmoQgSAJgJABQAbAiBFA+QAsAoAKAmQgLhIgVgoQgSgkgxg0QgDAHgVAJgAgZipQhAgOgUgzQAVAYBKAMQAmAGBSAFQAJgBAFABQAFABAAAGQAAAGANACIAQABQhBAHgvAAQgqAAgZgFg").shape;

		addChild(shape_8);
		addChild(shape_7);
		addChild(shape_6);
		addChild(shape_5);
		addChild(shape_4);
		addChild(shape_3);
		addChild(shape_2);
		addChild(shape_1);
		addChild(shape);
	}
}

class Player extends MovieClip {
	_Player_Forearm instance;
	_Player_Shoulder_Right instance_1;
	_Player_Head instance_2;
	_Player_Head_2 instance_3;
	_Player_Thigh_Right instance_4;
	_Player_Shin_Right instance_5;
	_Player_Chest_2 instance_6;
	_Player_Chest instance_7;
	_Player_Chest_3 instance_8;
	_Player_Thigh_Left instance_9;
	_Player_Shin_Left instance_10;
	_Player_Forearm_Left instance_11;
	_Player_Shoulder_Left instance_12;

	Player([String mode, int startPosition, bool loop])
			: super(mode, startPosition, loop, {"run":0}) {
		// timeline functions:
		void frame_29() {
			//gotoAndPlay(0);
		}

		// actions tween:
		timeline.addTween(_tween(this).wait(29).call(frame_29));

		// _Player_Forearm0
		instance = new _Player_Forearm()
		..setTransform(-18,-142.2,0.999,0.999,0.64)
		..applyCache(-8,-6,68,43);

		timeline.addTween(_tween(instance).to({"rotation":0.74,"x":-42.4,"y":-154},3).to({"rotation":1.40,"x":-51.3,"y":-212.1},3).to({"rotation":1.53,"x":-47.5,"y":-170.8},3).to({"regX":0,"rotation":1.36,"x":-36,"y":-131.2},3).to({"regX":0,"rotation":0.38,"x":-0.6,"y":-135.1},3).to({"rotation":-0.63,"x":23.6,"y":-139},3).to({"rotation":-1.63,"x":57.4,"y":-164.9},3).to({"rotation":-1.09,"x":37.3,"y":-127.8},3).to({"regX":0,"rotation":-0.02,"x":5.5,"y":-114.5},3).to({"scaleX":1,"scaleY":1,"rotation":0.42,"x":-10.1,"y":-133},2).wait(1));

		// _Player_Shoulder0
		instance_1 = new _Player_Shoulder_Right()
		..setTransform(2.4,-181.6,1,1,-0.16,0,0,0,0.1)
		..applyCache(-36,-12,51,53);

		timeline.addTween(_tween(instance_1).to({"rotation":0.09,"x":-11.4,"y":-187.2},3).to({"regY":0,"rotation":1.00,"x":-6.7,"y":-205.9},3).to({"regY":0.1,"rotation":0.61,"x":-6.2,"y":-182},3).to({"regY":0.2,"rotation":0.05,"x":-6.8,"y":-162.5},3).to({"regY":0.1,"rotation":-0.43,"x":7.8,"y":-177.5},3).to({"regX":0.1,"rotation":-0.88,"x":13.8,"y":-183.4},3).to({"regX":0,"regY":0,"rotation":-1.76,"x":18.4,"y":-187},3).to({"regY":0.1,"rotation":-0.96,"x":26.1,"y":-169},3).to({"regY":0.2,"rotation":-0.36,"x":19.7,"y":-154.7},3).to({"scaleX":1,"scaleY":1,"rotation":-0.23,"x":8.2,"y":-172.6},2).wait(1));

		// _Player_Head
		instance_2 = new _Player_Head()
		..setTransform(18.4,-238.2,1,1,-0.03)
		..off = true
		..applyCache(-32,-38,74,69);

		timeline.addTween(_tween(instance_2).wait(6).to({"off":false},0).to({"x":25.5,"y":-216.8},3).to({"x":22.9,"y":-199.2},3).to({"x":22.5,"y":-212.7},2).to({"off":true},1).wait(6).to({"x":18.4,"y":-237.9,"off":false},0).to({"x":25.5,"y":-216.8},3).to({"x":22.9,"y":-199.2},3).to({"x":22.5,"y":-212.9},2).wait(1));

		// _Player_Head
		instance_3 = new _Player_Head_2()
		..setTransform(22.3,-220,1,1,-0.03)
		..applyCache(-32,-34,72,66);

		timeline.addTween(_tween(instance_3).to({"x":17.7,"y":-225.6},3).to({"x":18.1,"y":-234},2).to({"off":true},1).wait(9).to({"x":22.3,"y":-219.5,"off":false},0).to({"x":17.7,"y":-225.6},3).to({"x":18.1,"y":-233.9},2).to({"off":true},1).wait(9));

		// _Player_Thigh0
		instance_4 = new _Player_Thigh_Right()
		..setTransform(-5.5,-107.5,1.092,1.083,0,0.32,0.52);

		timeline.addTween(_tween(instance_4).to({"skewX":-0.20,"skewY":-0.00,"x":-9.4,"y":-112.9,"mode":"independent"},3).to({"skewX":0.17,"skewY":0.36,"x":-18.6,"y":-125.5},3).to({"skewX":0.26,"skewY":0.46,"x":-13.2,"y":-107.1},3).to({"skewX":0.21,"skewY":0.40,"x":-18.4,"y":-95.4},3).to({"skewX":0.74,"skewY":0.94,"x":-21,"y":-108.1},3).to({"skewX":1.53,"skewY":1.73,"x":-31.5,"y":-111.6},3).to({"skewX":2.26,"skewY":2.46,"x":-34.8,"y":-131.9},3).to({"skewX":1.75,"skewY":1.95,"x":-28.2,"y":-112.1},3).to({"skewX":1.13,"skewY":1.33,"x":-18.4,"y":-95.4},3).to({"scaleX":1.09,"scaleY":1.08,"skewX":0.59,"skewY":0.79,"x":-10.2,"y":-103.4},2).wait(1));

		// _Player_Shin0
		instance_5 = new _Player_Shin_Right()
		..setTransform(35.6,-63.1,1.058,1.047,0,1.31,1.47)
		..applyCache(-23,-10,48,81);

		timeline.addTween(_tween(instance_5).to({"skewX":0.52,"skewY":0.68,"x":47.7,"y":-92.3},3).to({"scaleX":1.05,"skewX":-0.68,"skewY":-0.71,"x":27.5,"y":-85.9},3).to({"scaleX":1.06,"skewX":-0.19,"skewY":-0.03,"y":-64},3).to({"scaleX":1.13,"scaleY":0.97,"skewX":0.42,"skewY":0.03,"x":24.6,"y":-54.6},3).to({"scaleX":1.05,"scaleY":1.05,"skewX":0.84,"skewY":0.87,"x":-0.9,"y":-50.6},3).to({"scaleX":1.05,"skewX":0.69,"skewY":0.60,"x":-58.2,"y":-57},3).to({"scaleX":1.06,"skewX":2.55,"skewY":2.36,"x":-90.9,"y":-111.7},3).to({"scaleX":1.05,"skewX":2.34,"skewY":2.39,"x":-67.4,"y":-67.9},3).to({"scaleX":1.09,"scaleY":0.93,"skewX":1.99,"skewY":2.29,"x":-23.7,"y":-38.4},3).to({"scaleX":1.07,"scaleY":1.01,"skewX":1.54,"skewY":1.74,"x":15.8,"y":-54.8},2).wait(1));

		// _Player_Chest
		instance_6 = new _Player_Chest_2()
		..setTransform(-18,-106.6,1,1,0.37)
		..off = true
		..applyCache(-34,-103,63,114);

		timeline.addTween(_tween(instance_6).wait(18).to({"off":false},0).to({"rotation":0.41,"x":-24,"y":-121.8},3).to({"rotation":0.48,"x":-22.6,"y":-103.7},3).to({"scaleX":1,"scaleY":1,"rotation":0.43,"x":-20.1,"y":-90},2).to({"off":true},1).wait(3));

		// _Player_Chest
		instance_7 = new _Player_Chest()
		..setTransform(-24.1,-121.9,1,1,0.41)
		..off = true
		..applyCache(-35,-111,65,122);

		timeline.addTween(_tween(instance_7).wait(6).to({"off":false},0).to({"rotation":0.48,"x":-22.6,"y":-103.7},3).to({"scaleX":1,"scaleY":1,"rotation":0.43,"x":-20.1,"y":-90},2).to({"off":true},1).wait(18));

		// _Player_Chest
		instance_8 = new _Player_Chest_3()
		..setTransform(-18.3,-102.3,1,1,0.4)
		..applyCache(-28,-103,55,111);

		timeline.addTween(_tween(instance_8).to({"rotation":0.37,"x":-17.9,"y":-106.5},3).to({"scaleX":1,"scaleY":1,"rotation":0.39,"x":-21.9,"y":-116.6},2).to({"off":true},1).wait(6).to({"scaleX":1,"scaleY":1,"rotation":0.40,"x":-18.8,"y":-83.2,"off":false},0).to({"rotation":0.40,"x":-18.2,"y":-102.2},3).to({"scaleX":1,"scaleY":1,"rotation":0.38,"x":-18,"y":-105},2).to({"off":true},1).wait(9).to({"scaleX":1,"scaleY":1,"rotation":0.40,"x":-18.8,"y":-83.2,"off":false},0).to({"scaleX":1,"scaleY":1,"rotation":0.40,"x":-18.4,"y":-95.8},2).wait(1));

		// _Player_Thigh
		instance_9 = new _Player_Thigh_Left()
		..setTransform(-19.1,-109.1,1.13,1.208,0,0.75,0.68)
		..applyCache(-10,-9,68,44);

		timeline.addTween(_tween(instance_9).to({"skewX":1.56,"skewY":1.49,"x":-26.2,"y":-112.4},3).to({"skewX":2.38,"skewY":2.31,"x":-22.8,"y":-135},3).to({"skewX":1.85,"skewY":1.78,"x":-19.5,"y":-114.2},3).to({"skewX":1.07,"skewY":1.00,"x":-22.1,"y":-97.9},3).to({"skewX":0.29,"skewY":0.22,"x":-5.3,"y":-106.4},3).to({"skewX":-0.27,"skewY":-0.34,"x":-10.6,"y":-113},3).to({"skewX":0.28,"skewY":0.21,"x":-15.7,"y":-127.1},3).to({"skewX":0.23,"skewY":0.15,"x":-14.5,"y":-104.2},3).to({"skewX":0.25,"skewY":0.18,"x":-12.9,"y":-95.1},3).to({"scaleX":1.13,"scaleY":1.21,"skewX":0.58,"skewY":0.51,"x":-17,"y":-104.3},2).wait(1));

		// _Player_Shin
		instance_10 = new _Player_Shin_Left()
		..setTransform(0.7,-57.1,1.031,1.112,0,-2.01,-2.26)
		..applyCache(-51,-61,63,68);

		timeline.addTween(_tween(instance_10).to({"scaleX":1,"scaleY":1,"rotation":-1.90,"skewX":0.00,"skewY":0.00,"x":-49.8,"y":-58.3},3).to({"scaleX":1.06,"scaleY":1.21,"rotation":0.00,"skewX":-0.19,"skewY":-0.51,"x":-76.9,"y":-113.5},3).to({"scaleX":1,"scaleY":1,"rotation":-0.45,"skewX":0.00,"skewY":0.00,"x":-56.3,"y":-68.4},3).to({"scaleX":1,"scaleY":1,"rotation":-0.71,"x":-17.1,"y":-38.2},3).to({"scaleX":1,"scaleY":1.01,"rotation":0.00,"skewX":-1.43,"skewY":-1.40,"x":36,"y":-64},3).to({"scaleY":1,"skewX":-2.42,"skewY":-2.39,"x":47.6,"y":-98.4},3).to({"scaleX":1.06,"scaleY":1.21,"skewX":-3.40,"skewY":-3.73,"x":29.2,"y":-85.8},3).to({"scaleX":1.01,"scaleY":1.14,"skewX":-2.77,"skewY":-2.94,"x":31.1,"y":-67},3).to({"scaleX":0.97,"scaleY":1.05,"skewX":-2.22,"skewY":-2.44,"x":33.8,"y":-57.8},3).to({"scaleX":1.01,"scaleY":1.09,"skewX":-2.09,"skewY":-2.33,"x":11.6,"y":-57.3},2).wait(1));

		// _Player_Forearm
		instance_11 = new _Player_Forearm_Left()
		..setTransform(12,-136.7,0.996,0.996,0.74)
		..applyCache(-10,-6,65,29);

		timeline.addTween(_tween(instance_11).to({"rotation":-0.56,"x":26.6,"y":-139.6},3).to({"regY":0.1,"rotation":-1.45,"x":51.4,"y":-163.4},3).to({"rotation":-1.00,"x":40.9,"y":-136.7},3).to({"rotation":-0.22,"x":6.5,"y":-117.2},3).to({"regY":0,"rotation":1.00,"x":-3.1,"y":-148.4},3).to({"rotation":0.75,"x":-41.7,"y":-162.8},3).to({"regY":0.1,"rotation":1.80,"x":-50,"y":-208.3},3).to({"rotation":1.87,"x":-46.5,"y":-166.2},3).to({"regX":0,"rotation":1.19,"x":-29.5,"y":-134.1},3).to({"regY":0,"scaleX":1,"scaleY":1,"rotation":0.89,"x":-1.6,"y":-135.8},2).wait(1));

		// _Player_Shoulder
		instance_12 = new _Player_Shoulder_Left()
		..setTransform(10.9,-171.4,1.116,1.029,-0.03)
		..applyCache(-12,-10,29,56);

		timeline.addTween(_tween(instance_12).to({"rotation":-0.32,"x":16.8,"y":-172.9},3).to({"rotation":-0.95,"x":26.1,"y":-183.2},3).to({"rotation":-0.50,"x":25.3,"y":-167.8},3).to({"rotation":0.28,"x":17.5,"y":-150.2},3).to({"rotation":0.09,"x":1.2,"y":-183.1},3).to({"rotation":0.72,"x":-17.6,"y":-187.8},3).to({"rotation":1.51,"x":-17.7,"y":-208.5},3).to({"rotation":1.07,"x":-15.2,"y":-182.8},3).to({"rotation":0.64,"x":-8.4,"y":-163.2},3).to({"scaleX":1.12,"rotation":0.18,"x":4.4,"y":-168.6},2).wait(1));

	}
}



/* SHORTCUTS */

const _tween = TimelineTween.get;
const _ease = TransitionFunction.custom;
const _draw = _ShapeFactory.create;

class _ShapeFactory {
  Shape _shape;
  Graphics _graphics;
  Function _endFill;
  Function _endStroke;
  num _strokeWidth = 1;
  String _strokeJoints = "miter";
  String _strokeCaps = "butt";
  
  static _ShapeFactory create(num x, num y) {
    return new _ShapeFactory(x, y);
  }
  
  Shape get shape {
    ef(); es();
    return _shape;
  }
  Graphics get graphics {
    ef(); es();
    return _graphics;
  }
  
  _ShapeFactory(num x, num y) {
    _shape = new Shape();
    _graphics = _shape.graphics;
    _shape.x = x.toDouble();
    _shape.y = y.toDouble();
  }
  
  _ShapeFactory beginLinearGradientFill(List<int> colors, List<num> stops, num x0, num y0, num x1, num y1) {
    return lf(colors, stops, x0, y0, x1, y1);
  }
  _ShapeFactory beginRadialGradientFill(List<int> colors, List<num> stops, num x0, num y0, num r0, num x1, num y1, num r1) {
    return rf(colors, stops, x0, y0, r0, x1, y1, r1);
  }
  _ShapeFactory beginBitmapFill(Bitmap image, [String repeat, Matrix mat]) {
    return bf(image, repeat, mat);
  }
  _ShapeFactory beginFill([int color]) {
    return f(color);
  }
  _ShapeFactory endFill() {
    return ef();
  }
  _ShapeFactory beginStroke([int color]) {
    return s(color);
  }
  _ShapeFactory beginLinearGradientStroke(List<int> colors, List<num> stops, num x0, num y0, num x1, num y1) {
    return ls(colors, stops, x0, y0, x1, y1);
  }
  _ShapeFactory beginRadialGradientStroke(List<int> colors, List<num> stops, num x0, num y0, num r0, num x1, num y1, num r1) {
    return rs(colors, stops, x0, y0, r0, x1, y1, r1);
  }
  _ShapeFactory setStrokeStyle(num thickness, [caps, joints, num miterLimit=10, bool ignoreScale=false]) {
    return ss(thickness, caps, joints, miterLimit, ignoreScale);
  }
  _ShapeFactory closePath() {
    return cp();
  }
  
  _ShapeFactory moveTo(num x, num y) {
    _graphics.moveTo(x, y);
    return this;
  }
  _ShapeFactory lineTo(num x, num y) {
    _graphics.lineTo(x, y);
    return this;
  }
  _ShapeFactory curveTo(num cx, num cy, num x, num y) {
    _graphics.quadraticCurveTo(cx, cy, x, y);
    return this;
  }
  _ShapeFactory drawCircle(num x, num y, num radius) {
    return dc(x, y, radius);
  }
  _ShapeFactory drawEllipse(num x, num y, num width, num height) {
    return de(x, y, width, height);
  }
  _ShapeFactory drawRect(num x, num y, num width, num height) {
    return dr(x, y, width, height);
  }
  _ShapeFactory drawRectRounded(num x, num y, num width, num height, num radius) {
    return rr(x, y, width, height, radius);
  }
  _ShapeFactory drawPolyStar (num x, num y, num radius, num sides, num pointSize, num angle) {
    return dp(x, y, radius, sides, pointSize, angle);
  }
  
  // fills
  _ShapeFactory lf(List<int> colors, List<num> stops, num x0, num y0, num x1, num y1) {
    ef();
    var gradient = new GraphicsGradient.linear(x0, y0, x1, y1);
    int n = colors.length;
    for(int i = 0; i<n; i++) {
      gradient.addColorStop(stops[i], colors[i]);
    }
    _endFill = () {
      _graphics.fillGradient(gradient);
    };
    return this;
  }
  _ShapeFactory rf(List<int> colors, List<num> stops, num x0, num y0, num r0, num x1, num y1, num r1) {
    ef();
    var gradient = new GraphicsGradient.radial(x0, y0, r0, x1, y1, r1);
    int n = colors.length;
    for(int i = 0; i<n; i++) {
      gradient.addColorStop(stops[i], colors[i]);
    }
    _endFill = () {
      _graphics.fillGradient(gradient);
    };
    return this;
  }
  _ShapeFactory bf(Bitmap image, [String repeat, Matrix mat]) {
    var bmp = image.bitmapData;
    GraphicsPattern pattern = null;
    if (mat != null) mat.translate(-_shape.x, -_shape.y);
    else mat = new Matrix(1, 0, 0, 1, -_shape.x, -_shape.y);
    switch (repeat) {
      case "repeat-x": pattern = new GraphicsPattern.repeatX(bmp, mat); break;
      case "repeat-y": pattern = new GraphicsPattern.repeatY(bmp, mat); break;
      case "no-repeat": pattern = new GraphicsPattern.noRepeat(bmp, mat); break;
      default: pattern = new GraphicsPattern.repeat(bmp, mat); break;
    }
    _endFill = () {
      _graphics.fillPattern(pattern);
    };
    return this;
  }
  _ShapeFactory f([int color]) {
    if (color == null) color = 0;
    ef();
    _endFill = () {
      _graphics.fillColor(color);
    };
    return this;
  }
  _ShapeFactory ef() {
    if (_endFill != null) {
      _endFill();
      _endFill = null;
    }
    return this;
  }
  
  // stroke
  _ShapeFactory s([int color]) {
    es();
    if (color == null) color = 0;
    _endStroke = () {
      _graphics.strokeColor(color, _strokeWidth, _strokeJoints, _strokeCaps);
    };
    _graphics.beginPath();
    return this;
  }
  _ShapeFactory ls(List<int> colors, List<num> stops, num x0, num y0, num x1, num y1) {
    es();
    var gradient = new GraphicsGradient.linear(x0, y0, x1, y1);
    int n = colors.length;
    for(int i = 0; i<n; i++) {
      gradient.addColorStop(stops[i], colors[i]);
    }
    _endStroke = () {
      _graphics.strokeGradient(gradient, _strokeWidth, _strokeJoints, _strokeCaps);
    };
    return this;
  }
  _ShapeFactory rs(List<int> colors, List<num> stops, num x0, num y0, num r0, num x1, num y1, num r1) {
    es();
    var gradient = new GraphicsGradient.radial(x0, y0, r0, x1, y1, r1);
    int n = colors.length;
    for(int i = 0; i<n; i++) {
      gradient.addColorStop(stops[i], colors[i]);
    }
    _endStroke = () {
      _graphics.strokeGradient(gradient, _strokeWidth, _strokeJoints, _strokeCaps);
    };
    return this;
  }
  _ShapeFactory es() {
    if (_endStroke != null) {
      _endStroke();
      _endStroke = null;
    }
    return this;
  }
  _ShapeFactory ss(num thickness, [caps, joints, num miterLimit=10, bool ignoreScale=false]) {
    _strokeWidth = thickness;
    if (caps != null) {
      switch(caps) {
        case 0: _strokeCaps = "butt"; break;
        case 1: _strokeCaps = "round"; break;
        case 2: _strokeCaps = "square"; break;
        default: _strokeCaps = caps.toString(); break;
      }
    }
    else _strokeCaps = "butt";
    if (joints != null) {
      switch(joints) {
        case 0: _strokeJoints = "miter"; break;
        case 1: _strokeJoints = "round"; break;
        case 2: _strokeJoints = "bevel"; break;
        default: _strokeJoints = joints.toString(); break;
      }
    }
    else _strokeJoints = "miter";
    return this;
  }
  
  _ShapeFactory cp() {
    _graphics.closePath();
    return this;
  }
  _ShapeFactory mt(num x, num y) {
    _graphics.moveTo(x, y);
    return this;
  }
  _ShapeFactory lt(num x, num y) {
    _graphics.lineTo(x, y);
    return this;
  }
  _ShapeFactory c(num cx, num cy, num x, num y) {
    _graphics.quadraticCurveTo(cx, cy, x, y);
    return this;
  }
  _ShapeFactory dc(num x, num y, num radius) {
    _graphics.circle(x, y, radius);
    return this;
  }
  _ShapeFactory de(num x, num y, num width, num height) {
    _graphics.ellipse(x, y, width, height);
    return this;
  }
  _ShapeFactory dr(num x, num y, num width, num height) {
    _graphics.rect(x, y, width, height);
    return this;
  }
  _ShapeFactory rr(num x, num y, num width, num height, num radius) {
    _graphics.rectRound(x, y, width, height, radius, radius);
    return this;
  }
  _ShapeFactory dp(num x, num y, num radius, num sides, num pointSize, num angle) {
    // TODO PolyStar
    return this;
  }
  
  // decodePath
  _ShapeFactory p(String str) {
    _graphics.decode(str);
    return this;
  }
}
